name: Continuous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-slim
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4
            - name: Configure Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.9.3
            - name: Download Dependencies
              run: deno task deps:cache
            - name: Check Format
              run: deno task check:format
            - name: Check Types
              run: deno task check:types
            - name: Check Lint
              run: deno task check:lint
